version: "3.8"
services:
  hospitrack:
    command: >
      python -m debugpy --listen 0.0.0.0:5678 -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "5678:5678"
      - "8000:8000"